goals:
    - goal:
         x: 0
         y: 0
         theta: 0
      wavs:
          - 'welcome.wav'
    - goal:
         x: 11.4
         y: .999
         theta: 1.28
      wavs:
         - 'toasters.wav'
    - goal:
         x: 15.093
         y: 4.5
         theta: 0.758
      wavs:
         - 'leg1.wav'
    - goal:
         x: 21.82
         y: 5.6
         theta: 0
      wavs:
         - 'pokerface1.wav'
    - goal:
         x: -4.374
         y: -8.15
         theta: 4.71
      wavs:
         - 'dicks.wav'
    - goal:
         x: 0
         y: 0
         theta: 0
      wavs:
          - 'moveplz.wav'
