goals:
    - goal:
         x: -5.79
         y: 32.22
         theta: 3.76
      wavs:
          - 'blank_sound.ogg'
    - goal:
         x: -9
         y: 29.99
         theta: 3.76
      wavs:
         - 'blank_sound.ogg'
    - goal:
         x: -14.9
         y: 25.14
         theta: 3.76
      wavs:
         - 'blank_sound.ogg'
    - goal:
         x: -15.31
         y: 19.85
         theta: .95
      wavs:
         - 'blank_sound.ogg'
    - goal:
         x: -8.7
         y: 19.11
         theta: .57
      wavs:
         - 'blank_sound.ogg'
    - goal:
         x: -5.09
         y: 21.6
         theta: 2.16
      wavs:
         - 'blank_sound.ogg'
    - goal:
         x: -5.79
         y: 32.22
         theta: 3.76
      wavs:
          - 'blank_sound.ogg'
jokes:
    - 'joke1.wav'
    - 'joke2.wav'
    - 'joke3.wav'
    - 'joke4.wav'
